// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: simple.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SimpleRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SimpleRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SimpleRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SimpleRequestMultiError, or
// nil if none found.
func (m *SimpleRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SimpleRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := SimpleRequestValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetAge() <= 0 {
		err := SimpleRequestValidationError{
			field:  "Age",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return SimpleRequestMultiError(errors)
	}

	return nil
}

// SimpleRequestMultiError is an error wrapping multiple validation errors
// returned by SimpleRequest.ValidateAll() if the designated constraints
// aren't met.
type SimpleRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SimpleRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SimpleRequestMultiError) AllErrors() []error { return m }

// SimpleRequestValidationError is the validation error returned by
// SimpleRequest.Validate if the designated constraints aren't met.
type SimpleRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SimpleRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SimpleRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SimpleRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SimpleRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SimpleRequestValidationError) ErrorName() string { return "SimpleRequestValidationError" }

// Error satisfies the builtin error interface
func (e SimpleRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSimpleRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SimpleRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SimpleRequestValidationError{}

// Validate checks the field values on SimpleResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SimpleResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SimpleResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SimpleResponseMultiError,
// or nil if none found.
func (m *SimpleResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SimpleResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	if len(errors) > 0 {
		return SimpleResponseMultiError(errors)
	}

	return nil
}

// SimpleResponseMultiError is an error wrapping multiple validation errors
// returned by SimpleResponse.ValidateAll() if the designated constraints
// aren't met.
type SimpleResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SimpleResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SimpleResponseMultiError) AllErrors() []error { return m }

// SimpleResponseValidationError is the validation error returned by
// SimpleResponse.Validate if the designated constraints aren't met.
type SimpleResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SimpleResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SimpleResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SimpleResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SimpleResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SimpleResponseValidationError) ErrorName() string { return "SimpleResponseValidationError" }

// Error satisfies the builtin error interface
func (e SimpleResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSimpleResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SimpleResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SimpleResponseValidationError{}
